[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/home"
  to = "/home.html"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/project1"
  to = "/project1.html"
  status = 301

[[redirects]]
  from = "/project2"
  to = "/project2.html"
  status = 301

[[redirects]]
  from = "/project3"
  to = "/project3.html"
  status = 301

[[redirects]]
  from = "/project4"
  to = "/project4.html"
  status = 301

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 